# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-17 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0008_auto_20171217_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='ingredients',
        ),
        migrations.AddField(
            model_name='post',
            name='portions',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='prepare_time',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='preperation',
            field=models.TextField(blank=True),
        ),
    ]
