# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-17 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0009_auto_20171217_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='preview_text',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
